### ISSUE TITLE
Node check stops working for Deno 2

### ISSUE THREAD

**Issue by ycmjason** [dsherret/which-runtime#1]
`process` becomes available in Deno 2 so the check for Node no longer work.

**Comment by ycmjason** [comment]
A workaround I've been using is

```ts
const isNode: boolean = (globalThis as any).process?.argv0 === "node";
```

But I am not 100% if this is a foolproof check.

**Comment by dsherret** [comment]
Thanks! That's unfortunate. Should be fixed now.
